services:
  - type: web
    name: expense-tracker
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn expense_tracker.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: expense-tracker-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: RENDER
        value: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: "*"

databases:
  - name: expense-tracker-db
    databaseName: expense_tracker
    user: expense_tracker_user
